name = "FLOYao"
uuid = "6d9310a3-f1d0-41b7-8edb-11c1cf57cd2d"
authors = ["janlukas.bosse <janlukas.bosse@gmail.com> and contributors"]
version = "1.6.4"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SkewLinearAlgebra = "5c889d49-8c60-4500-9d10-5d3a22e2f4b9"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[compat]
SkewLinearAlgebra = "1"
Yao = "0.8.6, 0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
